### ISSUE TITLE
"connect ETIMEDOUT"

### ISSUE THREAD

**Issue by LuigiMario79** [edave64/Doki-Doki-Dialog-Generator#40] opened 2023-10-14 00:59 UTC
Sending convo-error Error: Could not fetch content pack: connect ETIMEDOUT 2606:50c0:8000::153:443
at Object.installContentPack (C:\Users[redacted]\AppData\Local\Programs\dddg-desktop-version\resources\app.asar\components\packManager.js:84:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async C:\Users[redacted]\AppData\Local\Programs\dddg-desktop-version\resources\app.asar\components\ipc-handlers\repo.js:10:3
at async C:\Users[redacted]\AppData\Local\Programs\dddg-desktop-version\resources\app.asar\components\ipc.js:97:17
at async IpcMainImpl. (C:\Users[redacted]\AppData\Local\Programs\dddg-desktop-version\resources\app.asar\components\ipc.js:168:4)

Can someone help me with this? This keeps popping up in the command prompt every time I try to use the store locally button on a content pack. And yes, I checked the antivirus and my connection, and uninstalled the program and reinstalled it.

**Comment by edave64** [comment] 2023-10-15 15:02
I understand that it must be very frustrating that I don't have a solution for you here. But there is no-one here except me. And as I told you, I have no clue. As far as I can see, there is nothing in DDDG that would trigger this error.

The best I can suggest to you is to manually do what the install pack process does:

- Download the project https://github.com/edave64/Doki-Doki-Dialog-Generator-Packs.
- Take the content pack you want
- Copy/Paste the folder of the content pack, e.g. "femc.mwroach.edave64" into the folder "C:\Users\[Username]\AppData\Roaming\dddg-desktop-version\localRepo".
- In that folder you just pasted, create a new file called "repo.json" with the following contents:

```
{
    "pack": {...},
    "authors": {}
}
```

But replace the "{...}" with the corresponding section from this file: https://github.com/edave64/Doki-Doki-Dialog-Generator-Packs/blob/gh-pages/repo.json. In that text, replace all occurances of "https://edave64.github.io/Doki-Doki-Dialog-Generator-Packs/packs" with "http://localhost:4716/repo".

For example, for femc, the repo.json should look like this:

```
{
    "pack": {
		"id": "femc.mwroach.edave64",
		"name": "FeMC (Switcheroo)",
		"characters": ["FeMC (Switcheroo)"],
		"authors": ["Black Rabbit Artworks", "MW Roach"],
		"kind": ["Characters"],
		"source": "https://reddit.com/bi0ulm/",
		"dddg1Path": "http://localhost:4716/repo/femc.mwroach.edave64/index.json",
		"dddg2Path": "http://localhost:4716/repo/femc.mwroach.edave64/index.json",
		"description": "<a href=\"https://reddit.com/bi0ulm/\">Art</a> by <a href=\"https://reddit.com/u/blackrabbitartworks\">Black Rabbit Artworks</a>, Original design by <a href=\"https://reddit.com/u/MWRoach\">MW Roach</a>",
		"preview": [
			"http://localhost:4716/repo/femc.mwroach.edave64/a.png",
			"http://localhost:4716/repo/femc.mwroach.edave64/1l.png",
			"http://localhost:4716/repo/femc.mwroach.edave64/1r.png"
		],
		"searchWords": []
	},
    "authors": {}
}
```

Now, the pack should be available locally, as if the tool had it installed it itself.

For now, I will close this as a duplicate of https://github.com/edave64/Doki-Doki-Dialog-Generator/issues/35, but if something about this description is unclear or doesn't work, feel free to ask. Though you might get an answer faster if you contact me on reddit ;)

As for the original issue, if I ever find the reason why it would produce that error or have reason to believe the issue might be fixed, I will tell you.

**Closed by edave64** 2023-10-15 15:02 UTC

**Comment by LuigiMario79** [comment] 2023-10-23 05:18
Thanks!
